In [3]:
import numpy as np

**The Basics**

In [39]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [10]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [14]:
#Get dimension
b.ndim

2

In [20]:
#Get shape
a .shape

(3,)

In [22]:
b.shape

(2, 3)

In [30]:
#Get type
a.dtype

dtype('int16')

In [51]:
b.dtype

dtype('float64')

In [41]:
#Get size
a.itemsize

2

In [53]:
b.itemsize

8

In [47]:
#Get total size
a.size*a.itemsize

6

In [49]:
#another way to do that is 
a.nbytes

6

In [61]:
b.size*b.itemsize

48

In [63]:
b.nbytes

48

**Accessing/Changining specific elements, rows, columns, etc**

In [365]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a.shape

(2, 7)

In [375]:
#Get a specific element [r, c]
c = a[1,5]
print(c)

#Get two elements
a[[1,1],[1, 5]]

13


array([ 9, 13])

In [19]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [23]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [25]:
a[0, 1:-1:2]

array([2, 4, 6])

In [37]:
a[1, 5] = 20
print(a)
a[:, 2] = 5
print(a)
a[:, 2] = [15,16]
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2 15  4  5  6  7]
 [ 8  9 16 11 12 20 14]]


3D example

In [45]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
#Get specific element (work outside in)
b[0,1,1]

4

In [55]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [69]:
b[:,1,:]= [[9,10],[11,12]]
print(b)

[[[ 1  2]
  [ 9 10]]

 [[ 5  6]
  [11 12]]]


**Initializing  Different Types of Arrays**

In [341]:
#All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [345]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
# All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [94]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [100]:
#Any other number(full_like)
np.full_like(a,4)  

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [108]:
#Random decimal numbers
np.random.rand(4,2,)

array([[0.01290085, 0.72316462],
       [0.94425845, 0.96681726],
       [0.1005839 , 0.00765691],
       [0.07877283, 0.8230105 ]])

In [106]:
np.random.random_sample(a.shape)

array([[0.02076265, 0.2274953 , 0.63507583, 0.12854749, 0.21599153,
        0.53309319, 0.60702373],
       [0.35952788, 0.73562582, 0.60998084, 0.38451408, 0.32447128,
        0.82630711, 0.66130193]])

In [110]:
#Random integer values
np.random.randint(7,size=(3,3))

array([[3, 3, 5],
       [3, 6, 3],
       [6, 4, 3]])

In [134]:
np.random.randint(-3,7,size=(3,3))

array([[ 3, -1,  1],
       [ 5, -2,  6],
       [ 4,  4, -2]])

In [347]:
#The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [349]:
#Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [156]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [351]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z #instead of 4 we can write -1
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be careful when copying array!!!**

In [361]:
a = np.array([1,2,3])
b = a
print(b)
b[0] = 100
print(b)
print(a)

#To prevent this 
a = np.array([1,2,3])
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]
[1 2 3]


**Mathematics**

In [229]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [223]:
a += 2
a

array([ 9, 10, 11, 12])

In [209]:
a - 2

array([-1,  0,  1,  2])

In [211]:
a * 2

array([2, 4, 6, 8])

In [213]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [231]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [233]:
a ** 2

array([ 1,  4,  9, 16])

In [239]:
#Take the sin
sin = np.sin(a)
print(sin)
cos = np.cos(a)
print(cos)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


**Linear Algebra**

In [353]:
#Matrix Multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [355]:
#Find the Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

**Statistics**

In [261]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [357]:
np.min(stats)

1

In [269]:
np.max(stats)

6

In [273]:
np.max(stats, axis=0)

array([4, 5, 6])

In [277]:
np.sum(stats, axis=1)

array([ 6, 15])

**Reorganizing Arrays**

In [290]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
after = before.reshape((2,2,2)) #as long as it has same number of values
print(after)

In [294]:
#Vertically stacking vectors 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [296]:
#Horizontal stacking vectors
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [300]:
h1 = np.ones((2,3))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

**Miscellaneous**

**Load Data from File**

In [327]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata )        

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


**Boolean Masking and Advanced Indexing**

In [317]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [319]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [323]:
#We can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [359]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [331]:
np.all(filedata > 59, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [337]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [339]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])