In [3]:
import numpy as np

**The Basics**

In [39]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [10]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [14]:
#Get dimension
b.ndim

2

In [20]:
#Get shape
a .shape

(3,)

In [22]:
b.shape

(2, 3)

In [30]:
#Get type
a.dtype

dtype('int16')

In [51]:
b.dtype

dtype('float64')

In [41]:
#Get size
a.itemsize

2

In [53]:
b.itemsize

8

In [47]:
#Get total size
a.size*a.itemsize

6

In [49]:
#another way to do that is 
a.nbytes

6

In [61]:
b.size*b.itemsize

48

In [63]:
b.nbytes

48

**Accessing/Changining specific elements, rows, columns, etc**

In [96]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a.shape

(2, 7)

In [17]:
#Get a specific element [r, c]
a[1, 5]

13

In [19]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [23]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [25]:
a[0, 1:-1:2]

array([2, 4, 6])

In [37]:
a[1, 5] = 20
print(a)
a[:, 2] = 5
print(a)
a[:, 2] = [15,16]
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2 15  4  5  6  7]
 [ 8  9 16 11 12 20 14]]


3D example

In [45]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
#Get specific element (work outside in)
b[0,1,1]

4

In [55]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [69]:
b[:,1,:]= [[9,10],[11,12]]
print(b)

[[[ 1  2]
  [ 9 10]]

 [[ 5  6]
  [11 12]]]


**Initializing  Different Types of Arrays**

In [82]:
#All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [84]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
# All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [94]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [100]:
#Any other number(full_like)
np.full_like(a,4)  

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [108]:
#Random decimal numbers
np.random.rand(4,2,)

array([[0.01290085, 0.72316462],
       [0.94425845, 0.96681726],
       [0.1005839 , 0.00765691],
       [0.07877283, 0.8230105 ]])

In [106]:
np.random.random_sample(a.shape)

array([[0.02076265, 0.2274953 , 0.63507583, 0.12854749, 0.21599153,
        0.53309319, 0.60702373],
       [0.35952788, 0.73562582, 0.60998084, 0.38451408, 0.32447128,
        0.82630711, 0.66130193]])

In [110]:
#Random integer values
np.random.randint(7,size=(3,3))

array([[3, 3, 5],
       [3, 6, 3],
       [6, 4, 3]])

In [134]:
np.random.randint(-3,7,size=(3,3))

array([[ 3, -1,  1],
       [ 5, -2,  6],
       [ 4,  4, -2]])

In [136]:
#The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
#Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [156]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [180]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z #instead of 4 we can write -1
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be careful when copying array!!!**

In [192]:
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]
